### ISSUE TITLE
Unable to connect to SQL 2016

### ISSUE THREAD

**Issue by salimagic** [1971Merlin/Kaseya-NOC#3]
I am not sure if this is compatible with MSSQL 2016, but we just upgraded Kaseya to use SQL 2016 and now the NOC isn't working. Anyone have any ideas? Thanks!

**Comment by 1971Merlin** [comment]
Should be compatible. You may need to upgrade the version of the Microsoft sql plugin for php, to one that supports sql 2016.

**Comment by salimagic** [comment]
I just installed ODBC 17 (which states it supports from SQL 2008 to 2017. Still getting the same issue. The credentials are correct, but I keep getting bumped back out to changing the settings. Now with version 17, it doesn't even look like it's making an attempt at connecting :(

**Comment by zeeliejm** [comment]
Hi Craig

Thanks for this. I followed the instructions but I am getting this error:

Fatal error: Uncaught Error: Call to undefined function sqlsrv_connect() in C:\xampp\htdocs\noc\dblogin.php:14 Stack trace: #0 C:\xampp\htdocs\noc\index.php(3): require_once() #1 {main} thrown in C:\xampp\htdocs\noc\dblogin.php on line 14
